version: "3.9"

services:
  my-app:
    container_name: Sistema-app
    build:
      context: .
      dockerfile: .docker/Dockerfile
    image: my-app
    environment:
      - "APACHE_LOG_DIR=/app"
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./:/var/www/html
      - ./.docker/apache:/etc/apache2/sites-available/ssl
      - .:/app
    depends_on:
      - db
      - phpmyadmin
    networks:
      - Sistema

  db:
    image: mysql:8.3.0
    container_name: Sistema-mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: "database"
      MYSQL_PASSWORD: "2202"
      MYSQL_ROOT_PASSWORD: "2202"
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - Sistema

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: Sistema-phpmyadmin
    restart: unless-stopped
    links:
      - db:db
    ports:
      - "8080:80"
    environment:
      MYSQL_USER: "root"
      MYSQL_PASSWORD: "2202"
      MYSQL_ROOT_PASSWORD: "2202"
    networks:
      - Sistema

volumes:
  mysql_data:

networks:
  Sistema:
    driver: bridge
