version: "3.8"
services:
    app:
        container_name: sistema-medico-views
        build:
            context: .
            dockerfile: Dockerfile
        ports:
            - "5174:5174"
        volumes:
            - ./:/var/www/html
        networks:
            - lion 
networks:
    lion:
        driver: bridge
